export enum LocalStoragekeys {
	APP_LANGUAGE = 'APP_LANGUAGE',
	TOKEN = 'TOKEN',
	CURRENT_THEME_NAME = 'CURRENT_THEME_NAME',
	CURRENT_THEME = 'CURRENT_THEME',
	JWT_TOKEN = 'JWT_TOKEN',
	SIGN = 'SIGN'
}
